# .github/workflows/ci.yml

# Name of the workflow, which will be displayed on the GitHub Actions tab.
name: Continuous Integration

# This section defines when the workflow will run.
on:
  # Run on pushes to the 'main' branch.
  push:
    branches: [ "main" ]
  # Run on any pull request that targets the 'main' branch.
  pull_request:
    branches: [ "main" ]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel.
jobs:
  # We'll define a single job called "build-and-test".
  build-and-test:
    # The type of machine to run the job on. 'ubuntu-latest' is a standard choice.
    runs-on: ubuntu-latest

    # A sequence of tasks that will be executed as part of the job.
    steps:
      # Step 1: Check out the repository's code so the workflow can access it.
      - name: Checkout code
        uses: actions/checkout@v4

      # Step 2: Set up the pnpm package manager.
      - name: Setup pnpm
        uses: pnpm/action-setup@v3
        with:
          version: 8

      # Step 3: Set up the Node.js environment.
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20.x'
          cache: 'pnpm' # Enable caching for pnpm to speed up installs

      # Step 4: Install all project dependencies.
      - name: Install dependencies
        run: pnpm install

      # Step 5: Run the linter to check for code style issues.
      - name: Run Linter
        run: pnpm lint

      # Step 6: Run the TypeScript compiler to check for type errors.
      - name: Check Types
        run: pnpm tsc --noEmit

      # Step 7: Run the production build to ensure the app is buildable.
      - name: Create Production Build
        # This 'env' block makes the repository secrets and variables available to the build command.
        # This is the crucial fix for the CI build failure.
        env:
          STRIPE_SECRET_KEY: ${{ secrets.STRIPE_SECRET_KEY }}
          STRIPE_WEBHOOK_SECRET: ${{ secrets.STRIPE_WEBHOOK_SECRET }}
          SUPABASE_SERVICE_ROLE_KEY: ${{ secrets.SUPABASE_SERVICE_ROLE_KEY }}
          DEMO_CLIENT_PASSWORD: ${{ secrets.DEMO_CLIENT_PASSWORD }}
          DEMO_THERAPIST_PASSWORD: ${{ secrets.DEMO_THERAPIST_PASSWORD }}
          NEXT_PUBLIC_SUPABASE_URL: ${{ vars.NEXT_PUBLIC_SUPABASE_URL }}
          NEXT_PUBLIC_SUPABASE_ANON_KEY: ${{ vars.NEXT_PUBLIC_SUPABASE_ANON_KEY }}
          NEXT_PUBLIC_SITE_URL: ${{ vars.NEXT_PUBLIC_SITE_URL }}
          NEXT_PUBLIC_STRIPE_PUBLISHABLE_KEY: ${{ vars.NEXT_PUBLIC_STRIPE_PUBLISHABLE_KEY }}
        run: pnpm build